// Generated by d3d12/shaders/transpile.py from shaders/analyze_rate_control.comp -- do not edit.
// Profile desktop; glslc defines: (none); dxc defines: (none)
struct RDOperation
{
    int quant;
    uint block_offset_saving;
};

struct QuantStats
{
    half square_error;
    uint16_t payload_cost;
};

struct BlockStats
{
    uint num_planes;
    QuantStats errors[15];
};

static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

RWByteAddressBuffer buckets : register(u0, space0);
RWByteAddressBuffer block_stats : register(u1, space0);
cbuffer Registers
{
    int2 registers_resolution : packoffset(c0);
    int2 registers_resolution_8x8_blocks : packoffset(c0.z);
    int registers_block_offset_8x8 : packoffset(c1);
    int registers_block_stride_8x8 : packoffset(c1.y);
    int registers_block_offset_32x32 : packoffset(c1.z);
    int registers_block_stride_32x32 : packoffset(c1.w);
    uint registers_total_wg_count : packoffset(c2);
    uint registers_num_blocks_aligned : packoffset(c2.y);
    uint registers_block_index_shamt : packoffset(c2.z);
};


static uint3 gl_WorkGroupID;
static uint gl_LocalInvocationIndex;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint gl_LocalInvocationIndex : SV_GroupIndex;
};

groupshared uint shared_rate_cost[16];
groupshared float shared_distortion[16];
groupshared uint shared_tmp[4];

uint spvBitfieldUExtract(uint Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint2 spvBitfieldUExtract(uint2 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint3 spvBitfieldUExtract(uint3 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint4 spvBitfieldUExtract(uint4 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

int spvBitfieldSExtract(int Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int2 spvBitfieldSExtract(int2 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int2 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int3 spvBitfieldSExtract(int3 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int3 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int4 spvBitfieldSExtract(int4 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int4 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

uint pw_subgroup_id()
{
    return gl_LocalInvocationIndex / WaveGetLaneCount();
}

uint distortion_to_bucket_index(float d, float cost, float d_base, float cost_base)
{
    if (cost == cost_base)
    {
        return 0u;
    }
    float index = 60.0f + (2.0f * log2(max(d - d_base, 0.0f) / (cost_base - cost)));
    return uint(max(index + 0.5f, 0.0f));
}

uint inclusive_max_clustered16(inout uint v)
{
    v = min(v, (112u + WaveGetLaneIndex()));
    for (uint i = 1u; i < 16u; i *= 2u)
    {
        uint up = WaveReadLaneAt(v, WaveGetLaneIndex() - i) + i;
        v = max(v, ((WaveGetLaneIndex() >= i) ? up : 0u));
    }
    return v;
}

void emit_rdo_operations()
{
    float cost;
    float distortion;
    if (WaveGetLaneIndex() < 16u)
    {
        cost = float(shared_rate_cost[WaveGetLaneIndex()]);
        distortion = shared_distortion[WaveGetLaneIndex()];
    }
    else
    {
        cost = float(shared_rate_cost[WaveGetLaneIndex()]);
        distortion = 1000000015047466219876688855040.0f;
    }
    float param = distortion;
    float param_1 = cost;
    float param_2 = shared_distortion[0];
    float param_3 = float(shared_rate_cost[0]);
    uint bucket_index = distortion_to_bucket_index(param, param_1, param_2, param_3);
    if (WaveGetLaneIndex() == 0u)
    {
        bucket_index = 0u;
    }
    uint param_4 = bucket_index;
    uint _149 = inclusive_max_clustered16(param_4);
    uint inclusive_bucket_index = _149;
    if (WaveGetLaneIndex() == 0u)
    {
        uint unquantized_cost = shared_rate_cost[0];
        uint _168;
        buckets.InterlockedAdd(4, unquantized_cost, _168);
    }
    else
    {
        if (WaveGetLaneIndex() < 16u)
        {
            uint saving = shared_rate_cost[WaveGetLaneIndex() - 1u] - shared_rate_cost[WaveGetLaneIndex()];
            if (saving != 0u)
            {
                int2 block32x32_index = int2(gl_WorkGroupID.xy);
                int block_index = (registers_block_offset_32x32 + (block32x32_index.y * registers_block_stride_32x32)) + block32x32_index.x;
                uint subdivision = uint(block_index >> int(registers_block_index_shamt));
                uint _231;
                buckets.InterlockedAdd(((inclusive_bucket_index * 16u) + subdivision) * 4 + 64, saving, _231);
                uint _240 = uint(block_index) + (inclusive_bucket_index * registers_num_blocks_aligned);
                RDOperation _250 = { int(WaveGetLaneIndex()), uint(block_index) | (saving << uint(16)) };
                buckets.Store<int>(_240 * 8 + 8256, _250.quant);
                buckets.Store<uint>(_240 * 8 + 8260, _250.block_offset_saving);
            }
        }
    }
}

void comp_main()
{
    uint index = WaveGetLaneIndex() + (WaveGetLaneCount() * pw_subgroup_id());
    int2 block32x32_index = int2(gl_WorkGroupID.xy);
    int2 local_block_index = int2(int(spvBitfieldUExtract(index, 0, 2)), int(spvBitfieldUExtract(index, 2, 2)));
    int2 block8x8_index = (int2(4, 4) * block32x32_index) + local_block_index;
    bool block8x8_in_range = all(bool2(block8x8_index.x < registers_resolution_8x8_blocks.x, block8x8_index.y < registers_resolution_8x8_blocks.y));
    int block_index_8x8 = (registers_block_offset_8x8 + (registers_block_stride_8x8 * block8x8_index.y)) + block8x8_index.x;
    uint num_active_planes;
    if (block8x8_in_range)
    {
        num_active_planes = block_stats.Load<uint>(block_index_8x8 * 64 + 0);
    }
    uint bit_index = index >> uint(4);
    QuantStats stats;
    for (uint i = bit_index; i < 16u; i += 4u)
    {
        float dist = 0.0f;
        uint cost = 0u;
        if (block8x8_in_range)
        {
            QuantStats _346;
            _346.square_error = block_stats.Load<half>(block_index_8x8 * 64 + min(i, num_active_planes) * 4 + 4);
            _346.payload_cost = block_stats.Load<uint16_t>(block_index_8x8 * 64 + min(i, num_active_planes) * 4 + 6);
            stats.square_error = _346.square_error;
            stats.payload_cost = _346.payload_cost;
            dist = float(stats.square_error);
            cost = uint(stats.payload_cost);
        }
        if (cost != 0u)
        {
            cost += 24u;
        }
        if (WaveGetLaneCount() == 16u)
        {
            cost = WaveActiveSum(cost);
            dist = WaveActiveSum(dist);
        }
        else
        {
            cost += WaveReadLaneAt(cost, WaveGetLaneIndex() ^ 1u);
            cost += WaveReadLaneAt(cost, WaveGetLaneIndex() ^ 2u);
            cost += WaveReadLaneAt(cost, WaveGetLaneIndex() ^ 4u);
            cost += WaveReadLaneAt(cost, WaveGetLaneIndex() ^ 8u);
            dist += WaveReadLaneAt(dist, WaveGetLaneIndex() ^ 1u);
            dist += WaveReadLaneAt(dist, WaveGetLaneIndex() ^ 2u);
            dist += WaveReadLaneAt(dist, WaveGetLaneIndex() ^ 4u);
            dist += WaveReadLaneAt(dist, WaveGetLaneIndex() ^ 8u);
        }
        if ((index & 15u) == 0u)
        {
            if (cost != 0u)
            {
                cost += 64u;
            }
            shared_rate_cost[i] = (cost + 31u) >> uint(5);
            shared_distortion[i] = dist;
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if (pw_subgroup_id() == 0u)
    {
        emit_rdo_operations();
    }
}

[WaveSize(64)]
[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
