// Generated by d3d12/shaders/transpile.py from shaders/analyze_rate_control_finalize.comp -- do not edit.
// Profile desktop; glslc defines: (none); dxc defines: (none)
static const uint3 gl_WorkGroupSize = uint3(512u, 1u, 1u);

RWByteAddressBuffer buckets : register(u0, space0);

static uint gl_LocalInvocationIndex;
struct SPIRV_Cross_Input
{
    uint gl_LocalInvocationIndex : SV_GroupIndex;
};

groupshared uint shared_scan[512];

void comp_main()
{
    uint4 v = buckets.Load<uint4>(gl_LocalInvocationIndex * 16 + 64);
    v.y += v.x;
    v.z += v.y;
    v.w += v.z;
    shared_scan[gl_LocalInvocationIndex] = v.w;
    GroupMemoryBarrierWithGroupSync();
    for (uint _step = 1u; _step < 256u; _step *= 2u)
    {
        GroupMemoryBarrierWithGroupSync();
        uint shuffled_up = 0u;
        if (gl_LocalInvocationIndex >= _step)
        {
            shuffled_up = shared_scan[gl_LocalInvocationIndex - _step];
        }
        GroupMemoryBarrierWithGroupSync();
        v += shuffled_up.xxxx;
        shared_scan[gl_LocalInvocationIndex] = v.w;
    }
    buckets.Store<uint4>(gl_LocalInvocationIndex * 16 + 64, v);
}

[WaveSize(64)]
[numthreads(512, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
