// Generated by d3d12/shaders/transpile.py from shaders/block_packing.comp -- do not edit.
// Profile desktop; glslc defines: (none); dxc defines: (none)
struct BlockMeta
{
    uint code_word;
    uint offset;
};

struct QuantStats
{
    half square_error;
    uint16_t payload_cost;
};

struct BlockStats
{
    uint num_planes;
    QuantStats errors[15];
};

struct BitstreamPacket
{
    uint offset;
    uint num_words;
};

static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

static const BlockMeta _568 = { 0u, 0u };

RWByteAddressBuffer payload_data : register(u3, space0);
RWByteAddressBuffer bitstream_data : register(u0, space0);
RWByteAddressBuffer quant_data : register(u5, space0);
RWByteAddressBuffer block_meta : register(u2, space0);
RWByteAddressBuffer block_stats : register(u4, space0);
RWByteAddressBuffer bitstream_meta : register(u1, space0);
cbuffer Registers
{
    int2 registers_resolution : packoffset(c0);
    int2 registers_resolution_32x32_blocks : packoffset(c0.z);
    int2 registers_resolution_8x8_blocks : packoffset(c1);
    uint registers_quant_resolution_code : packoffset(c1.z);
    uint registers_sequence_code : packoffset(c1.w);
    int registers_block_offset_32x32 : packoffset(c2);
    int registers_block_stride_32x32 : packoffset(c2.y);
    int registers_block_offset_8x8 : packoffset(c2.z);
    int registers_block_stride_8x8 : packoffset(c2.w);
};


static uint3 gl_WorkGroupID;
static uint gl_LocalInvocationIndex;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint gl_LocalInvocationIndex : SV_GroupIndex;
};

static uint pending_sign_write;
static uint pending_sign_mask;
groupshared uint shared_sign_bank[4][32];

uint spvBitfieldInsert(uint Base, uint Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint2 spvBitfieldInsert(uint2 Base, uint2 Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint3 spvBitfieldInsert(uint3 Base, uint3 Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint4 spvBitfieldInsert(uint4 Base, uint4 Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint spvBitfieldUExtract(uint Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint2 spvBitfieldUExtract(uint2 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint3 spvBitfieldUExtract(uint3 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint4 spvBitfieldUExtract(uint4 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

int spvBitfieldSExtract(int Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int2 spvBitfieldSExtract(int2 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int2 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int3 spvBitfieldSExtract(int3 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int3 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int4 spvBitfieldSExtract(int4 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int4 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

uint pw_subgroup_id()
{
    return gl_LocalInvocationIndex / WaveGetLaneCount();
}

uint quantize_code_word(inout uint control_word, inout int quant)
{
    if ((quant != 0) && (control_word != 0u))
    {
        int q_bits = int(spvBitfieldUExtract(control_word, 16, 4));
        int sub_quant = min(q_bits, quant);
        q_bits -= sub_quant;
        quant -= sub_quant;
        if (quant != 0)
        {
            quant = min(quant, 3);
            uint plane0 = control_word & 21845u;
            uint plane1 = (control_word & 43690u) >> uint(1);
            uint plane2 = plane0 & plane1;
            do
            {
                plane0 = plane1;
                plane1 = plane2;
                plane2 = 0u;
                quant--;
            } while (quant != 0);
            plane0 &= (~plane1);
            uint new_control_word = plane0 | (plane1 << uint(1));
            control_word = spvBitfieldInsert(control_word, new_control_word, 0, 16);
        }
        control_word = spvBitfieldInsert(control_word, uint(q_bits), 16, 4);
    }
    return control_word;
}

uint compute_required_8x8_size(uint control_word)
{
    int q_bits = int(spvBitfieldUExtract(control_word, 16, 4));
    uint lsbs = control_word & 21845u;
    uint msbs = control_word & 43690u;
    uint msbs_shift = msbs >> uint(1);
    msbs |= msbs_shift;
    return uint((int(countbits(lsbs)) + int(countbits(msbs))) + (q_bits * 8));
}

uint pw_clustered_add_16(inout uint v)
{
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 1u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 2u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 4u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 8u);
    return v;
}

uint modify_quant_code(inout uint code, int quant)
{
    int e = int(spvBitfieldUExtract(code, 3, 5));
    e = max((e - quant), 0);
    code = spvBitfieldInsert(code, uint(e), 3, 5);
    return code;
}

uint inclusive_add_clustered16(inout uint v)
{
    for (uint i = 1u; i < 16u; i *= 2u)
    {
        uint up = WaveReadLaneAt(v, WaveGetLaneIndex() - i);
        v += (((WaveGetLaneIndex() & 15u) >= i) ? up : 0u);
    }
    return v;
}

uint pw_load8_payload_data_pw_words8(uint i)
{
    return (payload_data.Load<uint>((i / 4u) * 4 + 8) >> ((i % 4u) * 8u)) & 255u;
}

void pw_store8_bitstream_data_data8(uint i, uint v)
{
    uint shift = (i % 4u) * 8u;
    uint _130;
    bitstream_data.InterlockedAnd((i / 4u) * 4 + 0, ~(255u << shift), _130);
    uint _138;
    bitstream_data.InterlockedOr((i / 4u) * 4 + 0, (v & 255u) << shift, _138);
}

uint copy_bytes(inout uint output_offset, inout uint input_offset, inout uint count)
{
    uint significant_mask = 0u;
    do
    {
        uint param = input_offset;
        uint in_data = pw_load8_payload_data_pw_words8(param);
        significant_mask |= in_data;
        uint _273 = output_offset;
        output_offset = _273 + uint(1);
        uint param_1 = _273;
        uint param_2 = in_data;
        pw_store8_bitstream_data_data8(param_1, param_2);
        count--;
        input_offset++;
    } while (count > 0u);
    return significant_mask;
}

void append_sign_plane(uint bank, inout uint local_sign_offset, uint sign_mask, inout uint significant_mask)
{
    while (significant_mask != 0u)
    {
        int bit = int(firstbitlow(significant_mask));
        significant_mask &= (significant_mask - 1u);
        int out_bit = int(local_sign_offset & 31u);
        pending_sign_write = spvBitfieldInsert(pending_sign_write, spvBitfieldUExtract(sign_mask, bit, 1), out_bit, 1);
        pending_sign_mask = spvBitfieldInsert(pending_sign_mask, 1u, out_bit, 1);
        if (out_bit == 31)
        {
            if (pending_sign_mask == 4294967295u)
            {
                shared_sign_bank[bank][local_sign_offset / 32u] = pending_sign_write;
            }
            else
            {
                uint _387;
                InterlockedAnd(shared_sign_bank[bank][local_sign_offset / 32u], ~pending_sign_mask, _387);
                uint _395;
                InterlockedOr(shared_sign_bank[bank][local_sign_offset / 32u], pending_sign_write & pending_sign_mask, _395);
            }
            pending_sign_mask = 0u;
        }
        local_sign_offset++;
    }
}

void flush_sign_plane(uint bank, uint local_sign_offset)
{
    if (pending_sign_mask != 0u)
    {
        uint _408;
        InterlockedAnd(shared_sign_bank[bank][local_sign_offset / 32u], ~pending_sign_mask, _408);
        uint _416;
        InterlockedOr(shared_sign_bank[bank][local_sign_offset / 32u], pending_sign_write & pending_sign_mask, _416);
        pending_sign_mask = 0u;
    }
}

void pw_store16_bitstream_data_data16(uint i, uint v)
{
    uint shift = (i % 2u) * 16u;
    uint _151;
    bitstream_data.InterlockedAnd((i / 2u) * 4 + 0, ~(65535u << shift), _151);
    uint _159;
    bitstream_data.InterlockedOr((i / 2u) * 4 + 0, (v & 65535u) << shift, _159);
}

void comp_main()
{
    pending_sign_write = 0u;
    pending_sign_mask = 0u;
    uint index = WaveGetLaneIndex() + (WaveGetLaneCount() * pw_subgroup_id());
    uint linear_block_32x32_index = index >> uint(4);
    int2 block32x32_index = int2(2, 2) * int2(gl_WorkGroupID.xy);
    block32x32_index.x += int(spvBitfieldUExtract(index, 4, 1));
    block32x32_index.y += int(spvBitfieldUExtract(index, 5, 1));
    int2 local_block_index = int2(int(spvBitfieldUExtract(index, 0, 2)), int(spvBitfieldUExtract(index, 2, 2)));
    int2 block8x8_index = (int2(4, 4) * block32x32_index) + local_block_index;
    bool in_range_8x8 = all(bool2(block8x8_index.x < registers_resolution_8x8_blocks.x, block8x8_index.y < registers_resolution_8x8_blocks.y));
    bool in_range_32x32 = all(bool2(block32x32_index.x < registers_resolution_32x32_blocks.x, block32x32_index.y < registers_resolution_32x32_blocks.y));
    uint num_bits_for_q = 0u;
    int quant;
    if (in_range_32x32)
    {
        int block_index = (registers_block_offset_32x32 + (registers_block_stride_32x32 * block32x32_index.y)) + block32x32_index.x;
        quant = quant_data.Load<int>(block_index * 4 + 0);
    }
    else
    {
        quant = 0;
    }
    BlockMeta meta;
    if (in_range_8x8)
    {
        int block_index_1 = (registers_block_offset_8x8 + (registers_block_stride_8x8 * block8x8_index.y)) + block8x8_index.x;
        BlockMeta _540;
        _540.code_word = block_meta.Load<uint>(block_index_1 * 8 + 0);
        _540.offset = block_meta.Load<uint>(block_index_1 * 8 + 4);
        meta.code_word = _540.code_word;
        meta.offset = _540.offset;
        uint num_planes = block_stats.Load<uint>(block_index_1 * 64 + 0);
        num_bits_for_q = uint(block_stats.Load<uint16_t>(block_index_1 * 64 + min(num_planes, uint(quant)) * 4 + 6));
    }
    else
    {
        meta = _568;
    }
    uint param = meta.code_word;
    int param_1 = quant;
    uint _575 = quantize_code_word(param, param_1);
    uint code_word = _575;
    bool active_code_word = (code_word & 65535u) != 0u;
    uint4 code_word_ballot = WaveActiveBallot(active_code_word);
    uint _592;
    if ((WaveGetLaneCount() >= 64u) && (linear_block_32x32_index >= 2u))
    {
        _592 = code_word_ballot.y;
    }
    else
    {
        _592 = code_word_ballot.x;
    }
    uint local_ballot = _592;
    uint _603;
    if (WaveGetLaneCount() >= 32u)
    {
        _603 = spvBitfieldUExtract(local_ballot, int(16u * (linear_block_32x32_index & 1u)), 16);
    }
    else
    {
        _603 = local_ballot;
    }
    local_ballot = _603;
    uint param_2 = code_word;
    uint required_plane_bytes = compute_required_8x8_size(param_2);
    uint required_sign_bits = num_bits_for_q - (required_plane_bytes * 8u);
    uint required_bits_with_meta = num_bits_for_q;
    if (required_bits_with_meta != 0u)
    {
        required_bits_with_meta += 24u;
    }
    bool _638 = all(bool2(block32x32_index.x < registers_resolution_32x32_blocks.x, block32x32_index.y < registers_resolution_32x32_blocks.y));
    bool _644;
    if (_638)
    {
        _644 = (index & 15u) == 15u;
    }
    else
    {
        _644 = _638;
    }
    bool writes_header = _644;
    uint param_3 = required_bits_with_meta;
    uint _648 = pw_clustered_add_16(param_3);
    uint payload_total_bits = _648;
    uint payload_total_words = (payload_total_bits + 31u) / 32u;
    if (payload_total_words != 0u)
    {
        payload_total_words += 2u;
    }
    uint global_payload_offset = 0u;
    if (writes_header && (payload_total_words != 0u))
    {
        uint _668;
        payload_data.InterlockedAdd(4, payload_total_words, _668);
        global_payload_offset = _668;
    }
    global_payload_offset = WaveReadLaneAt(global_payload_offset, WaveGetLaneIndex() | 15u);
    if (writes_header)
    {
        uint block_index_2 = uint((registers_block_offset_32x32 + (block32x32_index.y * registers_block_stride_32x32)) + block32x32_index.x);
        if (payload_total_words != 0u)
        {
            bitstream_data.Store<uint>((global_payload_offset + 0u) * 4 + 0, (local_ballot | (payload_total_words << uint(16))) | (registers_sequence_code << uint(28)));
            uint param_4 = registers_quant_resolution_code;
            int param_5 = quant;
            uint _713 = modify_quant_code(param_4, param_5);
            bitstream_data.Store<uint>((global_payload_offset + 1u) * 4 + 0, _713 | (block_index_2 << uint(8)));
        }
        BitstreamPacket _727 = { global_payload_offset, payload_total_words };
        bitstream_meta.Store<uint>(block_index_2 * 8 + 0, _727.offset);
        bitstream_meta.Store<uint>(block_index_2 * 8 + 4, _727.num_words);
    }
    uint total_subblocks = uint(int(countbits(local_ballot)));
    uint param_6 = required_sign_bits;
    uint _741 = inclusive_add_clustered16(param_6);
    uint total_sign_bits = _741;
    uint param_7 = required_plane_bytes;
    uint _745 = inclusive_add_clustered16(param_7);
    uint local_planes_offset = _745 - required_plane_bytes;
    uint local_sign_offset = total_sign_bits - required_sign_bits;
    uint global_planes_offset = ((4u * global_payload_offset) + (3u * total_subblocks)) + 8u;
    uint param_8 = required_plane_bytes;
    uint _763 = pw_clustered_add_16(param_8);
    uint global_sign_offset = global_planes_offset + _763;
    global_planes_offset += local_planes_offset;
    uint total_sign_bytes = (WaveReadLaneAt(total_sign_bits, WaveGetLaneIndex() | 15u) + 7u) / 8u;
    if (active_code_word)
    {
        uint block_header_offset = uint(int(countbits(spvBitfieldUExtract(local_ballot, 0, (local_block_index.y * 4) + local_block_index.x))));
        uint in_q_bits = spvBitfieldUExtract(meta.code_word, 16, 4);
        uint out_q_bits = spvBitfieldUExtract(code_word, 16, 4);
        uint input_offset = meta.offset;
        uint output_offset = global_planes_offset;
        for (int bit_offset = 0; bit_offset < 16; bit_offset += 2)
        {
            uint out_planes = spvBitfieldUExtract(code_word, bit_offset, 2) + out_q_bits;
            uint in_planes = spvBitfieldUExtract(meta.code_word, bit_offset, 2) + in_q_bits;
            if (in_planes != 0u)
            {
                in_planes++;
            }
            uint param_9 = input_offset;
            uint sign_plane = pw_load8_payload_data_pw_words8(param_9);
            if (out_planes != 0u)
            {
                uint param_10 = output_offset;
                uint param_11 = input_offset + 1u;
                uint param_12 = out_planes;
                uint _845 = copy_bytes(param_10, param_11, param_12);
                output_offset = param_10;
                uint significant_mask = _845;
                uint param_13 = linear_block_32x32_index;
                uint param_14 = local_sign_offset;
                uint param_15 = sign_plane;
                uint param_16 = significant_mask;
                append_sign_plane(param_13, param_14, param_15, param_16);
                local_sign_offset = param_14;
            }
            input_offset += in_planes;
        }
        uint param_17 = linear_block_32x32_index;
        uint param_18 = local_sign_offset;
        flush_sign_plane(param_17, param_18);
        uint param_19 = ((2u * global_payload_offset) + block_header_offset) + 4u;
        uint param_20 = code_word;
        pw_store16_bitstream_data_data16(param_19, param_20);
        uint param_21 = (((4u * global_payload_offset) + (2u * total_subblocks)) + block_header_offset) + 8u;
        uint param_22 = code_word >> uint(16);
        pw_store8_bitstream_data_data8(param_21, param_22);
    }
    uint _892 = index & 15u;
    for (uint i = _892; i < (total_sign_bytes / 4u); i += 16u)
    {
        uint sign_word = shared_sign_bank[linear_block_32x32_index][i];
        uint offset_8b = global_sign_offset + (4u * i);
        uint param_23 = offset_8b + 0u;
        uint param_24 = sign_word >> uint(0);
        pw_store8_bitstream_data_data8(param_23, param_24);
        uint param_25 = offset_8b + 1u;
        uint param_26 = sign_word >> uint(8);
        pw_store8_bitstream_data_data8(param_25, param_26);
        uint param_27 = offset_8b + 2u;
        uint param_28 = sign_word >> uint(16);
        pw_store8_bitstream_data_data8(param_27, param_28);
        uint param_29 = offset_8b + 3u;
        uint param_30 = sign_word >> uint(24);
        pw_store8_bitstream_data_data8(param_29, param_30);
    }
    uint _949 = (total_sign_bytes & 4294967292u) + (index & 15u);
    for (uint i_1 = _949; i_1 < total_sign_bytes; i_1 += 16u)
    {
        uint sign_word_1 = shared_sign_bank[linear_block_32x32_index][i_1 / 4u];
        uint offset_8b_1 = global_sign_offset + i_1;
        uint param_31 = offset_8b_1;
        uint param_32 = sign_word_1 >> (8u * (i_1 & 3u));
        pw_store8_bitstream_data_data8(param_31, param_32);
    }
}

[WaveSize(64)]
[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
