// Generated by d3d12/shaders/transpile.py from shaders/dwt.comp -- do not edit.
// Profile desktop; glslc defines: FP16=0 PRECISION=1; dxc defines: (none)
#ifndef SPIRV_CROSS_CONSTANT_ID_0
#define SPIRV_CROSS_CONSTANT_ID_0 false
#endif
static const bool DCShift = SPIRV_CROSS_CONSTANT_ID_0;
static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

cbuffer Registers
{
    int2 _117_resolution : packoffset(c0);
    float2 _117_inv_resolution : packoffset(c0.z);
    int2 _117_aligned_resolution : packoffset(c1);
};

Texture2DArray<float4> uTexture : register(t0, space0);
SamplerState _uTexture_sampler : register(s0, space0);
RWTexture2DArray<float4> uOutput : register(u1, space0);

static uint3 gl_WorkGroupID;
static uint gl_LocalInvocationIndex;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint gl_LocalInvocationIndex : SV_GroupIndex;
};

groupshared uint shared_block[20][41];
static uint local_index;

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

uint spvBitfieldUExtract(uint Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint2 spvBitfieldUExtract(uint2 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint3 spvBitfieldUExtract(uint3 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint4 spvBitfieldUExtract(uint4 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

int spvBitfieldSExtract(int Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int2 spvBitfieldSExtract(int2 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int2 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int3 spvBitfieldSExtract(int3 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int3 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int4 spvBitfieldSExtract(int4 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int4 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

uint pw_subgroup_id()
{
    return gl_LocalInvocationIndex / WaveGetLaneCount();
}

int2 unswizzle8x8(uint index)
{
    uint y = spvBitfieldUExtract(index, 0, 1);
    uint x = spvBitfieldUExtract(index, 1, 2);
    y |= (spvBitfieldUExtract(index, 3, 2) << uint(1));
    x |= (spvBitfieldUExtract(index, 5, 1) << uint(2));
    return int2(int(x), int(y));
}

float2 generate_mirror_uv(inout int2 coord)
{
    coord -= int2(bool2(coord.x < int2(0, 0).x, coord.y < int2(0, 0).y));
    coord += int2(1, 1);
    int2 end_mirrored_clamp = (int2(2, 2) * _117_aligned_resolution) - _117_resolution;
    int2 past_wrapped_coord = (coord + (int2(2, 2) * (_117_resolution - _117_aligned_resolution))) + int2(1, 1);
    int2 _141 = min(coord, _117_resolution);
    bool2 _145 = bool2(coord.x >= end_mirrored_clamp.x, coord.y >= end_mirrored_clamp.y);
    coord = int2(_145.x ? past_wrapped_coord.x : _141.x, _145.y ? past_wrapped_coord.y : _141.y);
    return float2(coord) * _117_inv_resolution;
}

void store_shared(uint y, uint x, float2 v)
{
    shared_block[y][x] = spvPackHalf2x16(v);
}

void load_image_with_apron()
{
    int2 base_coord = (int2(gl_WorkGroupID.xy) * int2(32, 32)) - int2(4, 4);
    uint param = local_index;
    int2 local_coord0 = int2(2, 2) * unswizzle8x8(param);
    int2 coord0 = base_coord + local_coord0;
    int2 param_1 = coord0;
    float2 _191 = generate_mirror_uv(param_1);
    float4 texels0 = float4(uTexture.GatherRed(_uTexture_sampler, float3(_191, 0.0f))).wzxy;
    int2 param_2 = coord0 + int2(16, 0);
    float2 _211 = generate_mirror_uv(param_2);
    float4 texels1 = float4(uTexture.GatherRed(_uTexture_sampler, float3(_211, 0.0f))).wzxy;
    int2 param_3 = coord0 + int2(0, 16);
    float2 _228 = generate_mirror_uv(param_3);
    float4 texels2 = float4(uTexture.GatherRed(_uTexture_sampler, float3(_228, 0.0f))).wzxy;
    int2 param_4 = coord0 + int2(16, 16);
    float2 _245 = generate_mirror_uv(param_4);
    float4 texels3 = float4(uTexture.GatherRed(_uTexture_sampler, float3(_245, 0.0f))).wzxy;
    if (DCShift)
    {
        texels0 -= 0.5f.xxxx;
        texels1 -= 0.5f.xxxx;
        texels2 -= 0.5f.xxxx;
        texels3 -= 0.5f.xxxx;
    }
    int local_coord0_y_half = local_coord0.y >> 1;
    uint param_5 = uint(local_coord0_y_half + 0);
    uint param_6 = uint(local_coord0.x + 0);
    float2 param_7 = texels0.xz;
    store_shared(param_5, param_6, param_7);
    uint param_8 = uint(local_coord0_y_half + 0);
    uint param_9 = uint(local_coord0.x + 1);
    float2 param_10 = texels0.yw;
    store_shared(param_8, param_9, param_10);
    uint param_11 = uint(local_coord0_y_half + 0);
    uint param_12 = uint(local_coord0.x + 16);
    float2 param_13 = texels1.xz;
    store_shared(param_11, param_12, param_13);
    uint param_14 = uint(local_coord0_y_half + 0);
    uint param_15 = uint(local_coord0.x + 17);
    float2 param_16 = texels1.yw;
    store_shared(param_14, param_15, param_16);
    uint param_17 = uint(local_coord0_y_half + 8);
    uint param_18 = uint(local_coord0.x + 0);
    float2 param_19 = texels2.xz;
    store_shared(param_17, param_18, param_19);
    uint param_20 = uint(local_coord0_y_half + 8);
    uint param_21 = uint(local_coord0.x + 1);
    float2 param_22 = texels2.yw;
    store_shared(param_20, param_21, param_22);
    uint param_23 = uint(local_coord0_y_half + 8);
    uint param_24 = uint(local_coord0.x + 16);
    float2 param_25 = texels3.xz;
    store_shared(param_23, param_24, param_25);
    uint param_26 = uint(local_coord0_y_half + 8);
    uint param_27 = uint(local_coord0.x + 17);
    float2 param_28 = texels3.yw;
    store_shared(param_26, param_27, param_28);
    int2 local_coord = int2(int(32u + (2u * (local_index % 4u))), int(2u * (local_index / 4u)));
    int2 param_29 = base_coord + local_coord;
    float2 _404 = generate_mirror_uv(param_29);
    float4 texels = float4(uTexture.GatherRed(_uTexture_sampler, float3(_404, 0.0f))).wzxy;
    if (DCShift)
    {
        texels -= 0.5f.xxxx;
    }
    uint param_30 = uint(local_coord.y >> 1);
    uint param_31 = uint(local_coord.x + 0);
    float2 param_32 = texels.xz;
    store_shared(param_30, param_31, param_32);
    uint param_33 = uint(local_coord.y >> 1);
    uint param_34 = uint(local_coord.x + 1);
    float2 param_35 = texels.yw;
    store_shared(param_33, param_34, param_35);
    int2 local_coord_1 = int2(int(2u * (local_index % 16u)), int(32u + (2u * (local_index / 16u))));
    int2 param_36 = base_coord + local_coord_1;
    float2 _466 = generate_mirror_uv(param_36);
    float4 texels_1 = float4(uTexture.GatherRed(_uTexture_sampler, float3(_466, 0.0f))).wzxy;
    if (DCShift)
    {
        texels_1 -= 0.5f.xxxx;
    }
    uint param_37 = uint(local_coord_1.y >> 1);
    uint param_38 = uint(local_coord_1.x + 0);
    float2 param_39 = texels_1.xz;
    store_shared(param_37, param_38, param_39);
    uint param_40 = uint(local_coord_1.y >> 1);
    uint param_41 = uint(local_coord_1.x + 1);
    float2 param_42 = texels_1.yw;
    store_shared(param_40, param_41, param_42);
    if (local_index < 16u)
    {
        int2 local_coord_2 = int2(int(32u + (2u * (local_index % 4u))), int(32u + (2u * (local_index / 4u))));
        int2 param_43 = base_coord + local_coord_2;
        float2 _532 = generate_mirror_uv(param_43);
        float4 texels_2 = float4(uTexture.GatherRed(_uTexture_sampler, float3(_532, 0.0f))).wzxy;
        if (DCShift)
        {
            texels_2 -= 0.5f.xxxx;
        }
        uint param_44 = uint(local_coord_2.y >> 1);
        uint param_45 = uint(local_coord_2.x + 0);
        float2 param_46 = texels_2.xz;
        store_shared(param_44, param_45, param_46);
        uint param_47 = uint(local_coord_2.y >> 1);
        uint param_48 = uint(local_coord_2.x + 1);
        float2 param_49 = texels_2.yw;
        store_shared(param_47, param_48, param_49);
    }
}

float2 load_shared(uint y, uint x)
{
    return spvUnpackHalf2x16(shared_block[y][x]);
}

void forward_transform8x2()
{
    int2 local_coord = int2(int(8u * (local_index % 4u)), int(local_index / 4u));
    float2 values[16];
    for (int i = 0; i < 16; i++)
    {
        uint param = uint(local_coord.y);
        uint param_1 = uint(local_coord.x + i);
        float2 v = load_shared(param, param_1);
        values[i] = v;
    }
    for (int i_1 = 1; i_1 < 15; i_1 += 2)
    {
        values[i_1] += ((values[i_1 - 1] + values[i_1 + 1]) * (-1.58613431453704833984375f));
    }
    for (int i_2 = 2; i_2 < 14; i_2 += 2)
    {
        values[i_2] += ((values[i_2 - 1] + values[i_2 + 1]) * (-0.052980117499828338623046875f));
    }
    for (int i_3 = 3; i_3 < 13; i_3 += 2)
    {
        values[i_3] += ((values[i_3 - 1] + values[i_3 + 1]) * 0.88291108608245849609375f);
    }
    for (int i_4 = 4; i_4 < 12; i_4 += 2)
    {
        values[i_4] += ((values[i_4 - 1] + values[i_4 + 1]) * 0.4435068666934967041015625f);
    }
    GroupMemoryBarrierWithGroupSync();
    for (int i_5 = 2; i_5 < 6; i_5++)
    {
        float2 a = values[(2 * i_5) + 0];
        float2 b = values[(2 * i_5) + 1];
        a *= 0.812893092632293701171875f;
        b *= 1.23017406463623046875f;
        float2 t0 = float2(a.x, b.x);
        float2 t1 = float2(a.y, b.y);
        int y_coord = (local_coord.x >> 1) + (i_5 - 2);
        uint param_2 = uint(y_coord);
        uint param_3 = uint((2 * local_coord.y) + 0);
        float2 param_4 = t0;
        store_shared(param_2, param_3, param_4);
        uint param_5 = uint(y_coord);
        uint param_6 = uint((2 * local_coord.y) + 1);
        float2 param_7 = t1;
        store_shared(param_5, param_6, param_7);
    }
}

void forward_transform4x2(bool active_lane, int y_offset)
{
    int2 local_coord = int2(int(4u * (local_index % 8u)), int((local_index / 8u) + uint(y_offset)));
    float2 values[12];
    if (active_lane)
    {
        for (int i = 0; i < 12; i++)
        {
            uint param = uint(local_coord.y);
            uint param_1 = uint(local_coord.x + i);
            float2 v = load_shared(param, param_1);
            values[i] = v;
        }
        for (int i_1 = 1; i_1 < 11; i_1 += 2)
        {
            values[i_1] += ((values[i_1 - 1] + values[i_1 + 1]) * (-1.58613431453704833984375f));
        }
        for (int i_2 = 2; i_2 < 10; i_2 += 2)
        {
            values[i_2] += ((values[i_2 - 1] + values[i_2 + 1]) * (-0.052980117499828338623046875f));
        }
        for (int i_3 = 3; i_3 < 9; i_3 += 2)
        {
            values[i_3] += ((values[i_3 - 1] + values[i_3 + 1]) * 0.88291108608245849609375f);
        }
        for (int i_4 = 4; i_4 < 8; i_4 += 2)
        {
            values[i_4] += ((values[i_4 - 1] + values[i_4 + 1]) * 0.4435068666934967041015625f);
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if (active_lane)
    {
        for (int i_5 = 2; i_5 < 4; i_5++)
        {
            float2 a = values[(2 * i_5) + 0];
            float2 b = values[(2 * i_5) + 1];
            a *= 0.812893092632293701171875f;
            b *= 1.23017406463623046875f;
            float2 t0 = float2(a.x, b.x);
            float2 t1 = float2(a.y, b.y);
            int y_coord = (local_coord.x >> 1) + (i_5 - 2);
            uint param_2 = uint(y_coord);
            uint param_3 = uint((2 * local_coord.y) + 0);
            float2 param_4 = t0;
            store_shared(param_2, param_3, param_4);
            uint param_5 = uint(y_coord);
            uint param_6 = uint((2 * local_coord.y) + 1);
            float2 param_7 = t1;
            store_shared(param_5, param_6, param_7);
        }
    }
}

void comp_main()
{
    local_index = (pw_subgroup_id() * WaveGetLaneCount()) + WaveGetLaneIndex();
    load_image_with_apron();
    GroupMemoryBarrierWithGroupSync();
    forward_transform8x2();
    bool param = local_index < 32u;
    int param_1 = 16;
    forward_transform4x2(param, param_1);
    GroupMemoryBarrierWithGroupSync();
    forward_transform8x2();
    GroupMemoryBarrierWithGroupSync();
    uint param_2 = local_index;
    int2 local_coord = unswizzle8x8(param_2);
    for (int y = local_coord.y; y < 16; y += 8)
    {
        int _1046 = local_coord.x * 2;
        for (int x = _1046; x < 32; x += 16)
        {
            uint param_3 = uint(y);
            uint param_4 = uint(x + 0);
            float2 v0 = load_shared(param_3, param_4);
            uint param_5 = uint(y);
            uint param_6 = uint(x + 1);
            float2 v1 = load_shared(param_5, param_6);
            int img_x = x >> 1;
            int img_y = y;
            int2 base_image_coord = (int2(gl_WorkGroupID.xy) * int2(16, 16)) + int2(img_x, img_y);
            uOutput[int3(base_image_coord, 0)] = v0.xxxx;
            uOutput[int3(base_image_coord, 2)] = v0.yyyy;
            uOutput[int3(base_image_coord, 1)] = v1.xxxx;
            uOutput[int3(base_image_coord, 3)] = v1.yyyy;
        }
    }
}

[WaveSize(64)]
[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
