// Generated by d3d12/shaders/transpile.py from shaders/resolve_rate_control.comp -- do not edit.
// Profile desktop; glslc defines: (none); dxc defines: SPIRV_CROSS_CONSTANT_ID_0=64
struct RDOperation
{
    int quant;
    uint block_offset_saving;
};

#ifndef SPIRV_CROSS_CONSTANT_ID_0
#define SPIRV_CROSS_CONSTANT_ID_0 1u
#endif
static const uint _171 = SPIRV_CROSS_CONSTANT_ID_0;
static const uint3 gl_WorkGroupSize = uint3(_171, 1u, 1u);

static const RDOperation _96 = { 0, 0u };

RWByteAddressBuffer buckets : register(u0, space0);
RWByteAddressBuffer quant_data : register(u1, space0);
cbuffer Registers
{
    uint registers_target_payload_size : packoffset(c0);
    uint registers_num_blocks_per_subdivision : packoffset(c0.y);
};


static uint3 gl_WorkGroupID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
};

uint spvBitfieldUExtract(uint Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint2 spvBitfieldUExtract(uint2 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint3 spvBitfieldUExtract(uint3 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint4 spvBitfieldUExtract(uint4 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

int spvBitfieldSExtract(int Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int2 spvBitfieldSExtract(int2 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int2 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int3 spvBitfieldSExtract(int3 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int3 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int4 spvBitfieldSExtract(int4 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int4 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

void comp_main()
{
    int required_savings_per_bucket = buckets.Load<int>(4) - int(registers_target_payload_size);
    if (gl_WorkGroupID.x != 0u)
    {
        int prev_bucket_total = buckets.Load<int>((gl_WorkGroupID.x - 1u) * 4 + 64);
        if (buckets.Load<int>(gl_WorkGroupID.x * 4 + 64) == prev_bucket_total)
        {
            return;
        }
        required_savings_per_bucket -= prev_bucket_total;
    }
    else
    {
        if (buckets.Load<int>(gl_WorkGroupID.x * 4 + 64) == 0)
        {
            return;
        }
    }
    if (required_savings_per_bucket <= 0)
    {
        return;
    }
    uint total_saved = 0u;
    uint i = 0u;
    for (;;)
    {
        bool _85 = i < registers_num_blocks_per_subdivision;
        bool _92;
        if (_85)
        {
            _92 = total_saved < uint(required_savings_per_bucket);
        }
        else
        {
            _92 = _85;
        }
        if (_92)
        {
            RDOperation op = _96;
            if ((i + WaveGetLaneIndex()) < registers_num_blocks_per_subdivision)
            {
                RDOperation _118;
                _118.quant = buckets.Load<int>((((gl_WorkGroupID.x * registers_num_blocks_per_subdivision) + i) + WaveGetLaneIndex()) * 8 + 8256);
                _118.block_offset_saving = buckets.Load<uint>((((gl_WorkGroupID.x * registers_num_blocks_per_subdivision) + i) + WaveGetLaneIndex()) * 8 + 8260);
                op.quant = _118.quant;
                op.block_offset_saving = _118.block_offset_saving;
            }
            uint saving = spvBitfieldUExtract(op.block_offset_saving, 16, 16);
            uint block_offset = spvBitfieldUExtract(op.block_offset_saving, 0, 16);
            uint scan_saving = WavePrefixSum(saving) + saving;
            bool should_apply_quant = ((total_saved + scan_saving) - saving) < uint(required_savings_per_bucket);
            if (should_apply_quant && (saving != 0u))
            {
                int _160;
                quant_data.InterlockedMax(block_offset * 4 + 0, op.quant, _160);
            }
            total_saved += WaveReadLaneAt(scan_saving, WaveGetLaneCount() - 1u);
            i += WaveGetLaneCount();
            continue;
        }
        else
        {
            break;
        }
    }
}

[WaveSize(64)]
[numthreads(SPIRV_CROSS_CONSTANT_ID_0, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    comp_main();
}
