// Generated by d3d12/shaders/transpile.py from shaders/wavelet_quant.comp -- do not edit.
// Profile desktop; glslc defines: (none); dxc defines: (none)
struct QuantResult
{
    float square_error;
    int encode_cost_early;
    int block4x2_shifted;
    int encode_cost_late_bits;
    int quality_planes;
};

#ifndef SPIRV_CROSS_CONSTANT_ID_1
#define SPIRV_CROSS_CONSTANT_ID_1 false
#endif
static const bool SkipQuantScale = SPIRV_CROSS_CONSTANT_ID_1;

struct ResType
{
    float _m0;
    int _m1;
};

struct BlockMeta
{
    uint code_word;
    uint offset;
};

struct QuantStats
{
    half square_error;
    uint16_t payload_cost;
};

struct BlockStats
{
    uint num_planes;
    QuantStats errors[15];
};

static const uint3 gl_WorkGroupSize = uint3(128u, 1u, 1u);

static const BlockMeta _615 = { 0u, 0u };
static const QuantStats _638 = { half(0.0), 0u };

RWByteAddressBuffer payload_data : register(u3, space0);
RWByteAddressBuffer block_meta : register(u1, space0);
RWByteAddressBuffer block_stats : register(u2, space0);
cbuffer Registers
{
    int2 registers_resolution : packoffset(c0);
    int2 registers_resolution_8x8_blocks : packoffset(c0.z);
    float2 registers_inv_resolution : packoffset(c1);
    float registers_input_layer : packoffset(c1.z);
    float registers_quant_resolution : packoffset(c1.w);
    int registers_block_offset : packoffset(c2);
    int registers_block_stride : packoffset(c2.y);
    float registers_rdo_distortion_scale : packoffset(c2.z);
};

Texture2DArray<float4> uTexture : register(t0, space0);
SamplerState _uTexture_sampler : register(s0, space0);

static uint3 gl_WorkGroupID;
static uint gl_LocalInvocationIndex;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint gl_LocalInvocationIndex : SV_GroupIndex;
};

uint spvBitfieldInsert(uint Base, uint Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint2 spvBitfieldInsert(uint2 Base, uint2 Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint3 spvBitfieldInsert(uint3 Base, uint3 Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint4 spvBitfieldInsert(uint4 Base, uint4 Insert, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : (((1u << Count) - 1) << (Offset & 31));
    return (Base & ~Mask) | ((Insert << Offset) & Mask);
}

uint spvBitfieldUExtract(uint Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint2 spvBitfieldUExtract(uint2 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint3 spvBitfieldUExtract(uint3 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

uint4 spvBitfieldUExtract(uint4 Base, uint Offset, uint Count)
{
    uint Mask = Count == 32 ? 0xffffffff : ((1 << Count) - 1);
    return (Base >> Offset) & Mask;
}

int spvBitfieldSExtract(int Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int2 spvBitfieldSExtract(int2 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int2 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int3 spvBitfieldSExtract(int3 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int3 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

int4 spvBitfieldSExtract(int4 Base, int Offset, int Count)
{
    int Mask = Count == 32 ? -1 : ((1 << Count) - 1);
    int4 Masked = (Base >> Offset) & Mask;
    int ExtendShift = (32 - Count) & 31;
    return (Masked << ExtendShift) >> ExtendShift;
}

uint pw_subgroup_id()
{
    return gl_LocalInvocationIndex / WaveGetLaneCount();
}

int2 unswizzle8x8(uint index)
{
    uint y = spvBitfieldUExtract(index, 0, 1);
    uint x = spvBitfieldUExtract(index, 1, 2);
    y |= (spvBitfieldUExtract(index, 3, 2) << uint(1));
    x |= (spvBitfieldUExtract(index, 5, 1) << uint(2));
    return int2(int(x), int(y));
}

float max4(float4 v)
{
    float2 v2 = max(v.xy, v.zw);
    return max(v2.x, v2.y);
}

float pw_clustered_max_8(inout float v)
{
    v = max(v, WaveReadLaneAt(v, WaveGetLaneIndex() ^ 1u));
    v = max(v, WaveReadLaneAt(v, WaveGetLaneIndex() ^ 2u));
    v = max(v, WaveReadLaneAt(v, WaveGetLaneIndex() ^ 4u));
    return v;
}

uint encode_quant_scale(float scale)
{
    return uint(ceil((scale - 0.25f) * 8.0f));
}

float decode_quant_scale(uint code)
{
    return (float(code) / 8.0f) + 0.25f;
}

void compute_quant_scale(float max_wave_texels, inout uint quant_code, out float quant_scale)
{
    if (SkipQuantScale || (max_wave_texels < 1.0f))
    {
        quant_code = 6u;
        quant_scale = 1.0f;
    }
    else
    {
        ResType _284;
        _284._m0 = frexp(max_wave_texels - 0.25f, _284._m1);
        int e = _284._m1;
        float target_max = float(1 << e) - 0.25f;
        float inv_scale = max_wave_texels / target_max;
        float param = inv_scale;
        quant_code = encode_quant_scale(param);
        uint param_1 = quant_code;
        quant_scale = 1.0f / decode_quant_scale(param_1);
    }
}

uint pw_clustered_add_8(inout uint v)
{
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 1u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 2u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 4u);
    return v;
}

float compute_square_error(inout float2x4 v, int q, inout uint num_significant_values)
{
    v = float2x4(float4(abs(v[0])), float4(abs(v[1])));
    float2x4 iv = float2x4(float4(floor(ldexp(v[0], (-q).xxxx))), float4(trunc(ldexp(v[1], (-q).xxxx))));
    num_significant_values = 0u;
    for (int j = 0; j < 2; j++)
    {
        for (int i = 0; i < 4; i++)
        {
            if (iv[j][i] != 0.0f)
            {
                num_significant_values++;
            }
        }
    }
    bool4 _384 = bool4(iv[0].x != 0.0f.xxxx.x, iv[0].y != 0.0f.xxxx.y, iv[0].z != 0.0f.xxxx.z, iv[0].w != 0.0f.xxxx.w);
    iv[0] += float4(_384.x ? 0.5f.xxxx.x : 0.0f.xxxx.x, _384.y ? 0.5f.xxxx.y : 0.0f.xxxx.y, _384.z ? 0.5f.xxxx.z : 0.0f.xxxx.z, _384.w ? 0.5f.xxxx.w : 0.0f.xxxx.w);
    bool4 _392 = bool4(iv[1].x != 0.0f.xxxx.x, iv[1].y != 0.0f.xxxx.y, iv[1].z != 0.0f.xxxx.z, iv[1].w != 0.0f.xxxx.w);
    iv[1] += float4(_392.x ? 0.5f.xxxx.x : 0.0f.xxxx.x, _392.y ? 0.5f.xxxx.y : 0.0f.xxxx.y, _392.z ? 0.5f.xxxx.z : 0.0f.xxxx.z, _392.w ? 0.5f.xxxx.w : 0.0f.xxxx.w);
    iv = float2x4(float4(trunc(ldexp(iv[0], q.xxxx))), float4(trunc(ldexp(iv[1], q.xxxx))));
    float2x4 err = float2x4(v[0] - iv[0], v[1] - iv[1]);
    uint param = num_significant_values;
    uint _433 = pw_clustered_add_8(param);
    num_significant_values = _433;
    return (dot(err[0], err[0]) + dot(err[1], err[1])) * registers_rdo_distortion_scale;
}

int pw_clustered_add_8(inout int v)
{
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 1u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 2u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 4u);
    return v;
}

QuantResult compute_quant_stats(float2x4 v, int q, inout int msb, inout int block4x2_max, float inv_quant_squared)
{
    block4x2_max = block4x2_max >> q;
    float2x4 param = v;
    int param_1 = q;
    uint param_2;
    float _466 = compute_square_error(param, param_1, param_2);
    uint wave8_num_significants = param_2;
    QuantResult result;
    result.square_error = _466 * inv_quant_squared;
    result.block4x2_shifted = block4x2_max;
    result.encode_cost_early = int(block4x2_max > 0);
    msb -= q;
    result.quality_planes = 0;
    if (msb >= 3)
    {
        result.quality_planes = msb - 2;
        result.encode_cost_early = result.quality_planes + 1;
        result.block4x2_shifted = result.block4x2_shifted >> result.quality_planes;
    }
    result.encode_cost_early += (firstbithigh(result.block4x2_shifted) + 1);
    int param_3 = max((result.encode_cost_early - 1), 0);
    int _512 = pw_clustered_add_8(param_3);
    result.encode_cost_late_bits = (8 * _512) + int(wave8_num_significants);
    return result;
}

int scan_clustered8(inout int v)
{
    for (uint i = 1u; i < 8u; i *= 2u)
    {
        int up = WaveReadLaneAt(v, WaveGetLaneIndex() - i);
        v += (((WaveGetLaneIndex() & 7u) >= i) ? up : 0);
    }
    return v;
}

float pw_clustered_add_8(inout float v)
{
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 1u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 2u);
    v += WaveReadLaneAt(v, WaveGetLaneIndex() ^ 4u);
    return v;
}

void pw_store8_payload_data_pw_words8(uint i, uint v)
{
    uint shift = (i % 4u) * 8u;
    uint _219;
    payload_data.InterlockedAnd((i / 4u) * 4 + 8, ~(255u << shift), _219);
    uint _227;
    payload_data.InterlockedOr((i / 4u) * 4 + 8, (v & 255u) << shift, _227);
}

void encode_payload(int2 block_index_8x8, inout float2x4 texels)
{
    float4 param = abs(texels[0]);
    float4 param_1 = abs(texels[1]);
    float max_subblock_texel = max(max4(param), max4(param_1));
    float param_2 = max_subblock_texel;
    float _536 = pw_clustered_max_8(param_2);
    float max_wave_texels = _536;
    float param_3 = max_wave_texels;
    uint param_4;
    float param_5;
    compute_quant_scale(param_3, param_4, param_5);
    uint quant_code = param_4;
    float quant_scale = param_5;
    precise float2x4 _548 = texels * quant_scale;
    texels = _548;
    precise float _551 = max_wave_texels * quant_scale;
    max_wave_texels = _551;
    precise float _554 = max_subblock_texel * quant_scale;
    max_subblock_texel = _554;
    float overall_quant_scale = registers_quant_resolution * quant_scale;
    float inv_quant = 1.0f / overall_quant_scale;
    float inv_quant_squared = inv_quant * inv_quant;
    int4 abs_quant_texels0 = abs(int4(texels[0]));
    int4 abs_quant_texels1 = abs(int4(texels[1]));
    int max_absolute_value = int(max_wave_texels);
    int block4x2_max = int(max_subblock_texel);
    uint block_index = uint((registers_block_offset + (block_index_8x8.y * registers_block_stride)) + block_index_8x8.x);
    if (max_absolute_value == 0)
    {
        if ((WaveGetLaneIndex() & 7u) == 0u)
        {
            block_meta.Store<uint>(block_index * 8 + 0, _615.code_word);
            block_meta.Store<uint>(block_index * 8 + 4, _615.offset);
            block_stats.Store<uint>(block_index * 64 + 0, 0u);
            block_stats.Store<half>(block_index * 64 + 4, _638.square_error);
            block_stats.Store<uint16_t>(block_index * 64 + 6, _638.payload_cost);
        }
        return;
    }
    int msb = firstbithigh(max_absolute_value);
    float2x4 param_6 = texels;
    int param_7 = 0;
    int param_8 = msb;
    int param_9 = block4x2_max;
    float param_10 = inv_quant_squared;
    QuantResult _661 = compute_quant_stats(param_6, param_7, param_8, param_9, param_10);
    QuantResult result = _661;
    int param_11 = result.encode_cost_early;
    int _666 = scan_clustered8(param_11);
    int scan = _666;
    uint global_offset = 0u;
    if ((WaveGetLaneIndex() & 7u) == 7u)
    {
        uint _676;
        payload_data.InterlockedAdd(0, uint(scan), _676);
        global_offset = _676;
    }
    global_offset = WaveReadLaneAt(global_offset, WaveGetLaneIndex() | 7u);
    scan -= result.encode_cost_early;
    int quality_planes = result.quality_planes;
    uint code_word = uint(quality_planes << 16);
    code_word = spvBitfieldInsert(code_word, quant_code, 20, 4);
    uint plane_code = uint(firstbithigh(result.block4x2_shifted) + 1);
    uint merged_plane_code = plane_code << ((WaveGetLaneIndex() & 7u) * 2u);
    merged_plane_code |= WaveReadLaneAt(merged_plane_code, WaveGetLaneIndex() ^ 1u);
    merged_plane_code |= WaveReadLaneAt(merged_plane_code, WaveGetLaneIndex() ^ 2u);
    merged_plane_code |= WaveReadLaneAt(merged_plane_code, WaveGetLaneIndex() ^ 4u);
    code_word |= merged_plane_code;
    if ((WaveGetLaneIndex() & 7u) == 0u)
    {
        BlockMeta _732 = { code_word, global_offset };
        block_meta.Store<uint>(block_index * 8 + 0, _732.code_word);
        block_meta.Store<uint>(block_index * 8 + 4, _732.offset);
        block_stats.Store<uint>(block_index * 64 + 0, uint(msb + 1));
        QuantStats _749 = { half(0.0), (int16_t(result.encode_cost_late_bits)) };
        block_stats.Store<half>(block_index * 64 + 4, _749.square_error);
        block_stats.Store<uint16_t>(block_index * 64 + 6, _749.payload_cost);
    }
    for (int q = 1; q <= msb; q++)
    {
        float2x4 param_12 = texels;
        int param_13 = q;
        int param_14 = msb;
        int param_15 = block4x2_max;
        float param_16 = inv_quant_squared;
        QuantResult _775 = compute_quant_stats(param_12, param_13, param_14, param_15, param_16);
        QuantResult quant_result = _775;
        float param_17 = quant_result.square_error;
        float _780 = pw_clustered_add_8(param_17);
        float square_error = _780;
        if ((WaveGetLaneIndex() & 7u) == 0u)
        {
            QuantStats _796 = { half(min(square_error, 60000.0f)), (int16_t(quant_result.encode_cost_late_bits)) };
            block_stats.Store<half>(block_index * 64 + q * 4 + 4, _796.square_error);
            block_stats.Store<uint16_t>(block_index * 64 + q * 4 + 6, _796.payload_cost);
        }
    }
    float param_18 = (dot(texels[0], texels[0]) + dot(texels[1], texels[1])) * inv_quant_squared;
    float _819 = pw_clustered_add_8(param_18);
    float square_error_1 = _819;
    if ((WaveGetLaneIndex() & 7u) == 0u)
    {
        int _827 = msb + 1;
        QuantStats _831 = { half(min(60000.0f, square_error_1)), 0u };
        block_stats.Store<half>(block_index * 64 + _827 * 4 + 4, _831.square_error);
        block_stats.Store<uint16_t>(block_index * 64 + _827 * 4 + 6, _831.payload_cost);
    }
    uint byte_offset = uint(scan) + global_offset;
    bool need_sign = (result.block4x2_shifted != 0) || (quality_planes != 0);
    if (need_sign)
    {
        uint4 s0 = uint4(bool4(texels[0].x < 0.0f.xxxx.x, texels[0].y < 0.0f.xxxx.y, texels[0].z < 0.0f.xxxx.z, texels[0].w < 0.0f.xxxx.w)) << uint4(0u, 1u, 2u, 3u);
        uint4 s1 = uint4(bool4(texels[1].x < 0.0f.xxxx.x, texels[1].y < 0.0f.xxxx.y, texels[1].z < 0.0f.xxxx.z, texels[1].w < 0.0f.xxxx.w)) << uint4(4u, 5u, 6u, 7u);
        uint s = ((((((s0.x | s0.y) | s0.z) | s0.w) | s1.x) | s1.y) | s1.z) | s1.w;
        uint _896 = byte_offset;
        byte_offset = _896 + uint(1);
        uint param_19 = _896;
        uint param_20 = s;
        pw_store8_payload_data_pw_words8(param_19, param_20);
        int plane_iterations = quality_planes + int(plane_code);
        int _909 = plane_iterations - 1;
        int q_1 = _909;
        do
        {
            s0 = uint4(spvBitfieldUExtract(uint(abs_quant_texels0.x), q_1, 1), spvBitfieldUExtract(uint(abs_quant_texels0.y), q_1, 1), spvBitfieldUExtract(uint(abs_quant_texels0.z), q_1, 1), spvBitfieldUExtract(uint(abs_quant_texels0.w), q_1, 1));
            s1 = uint4(spvBitfieldUExtract(uint(abs_quant_texels1.x), q_1, 1), spvBitfieldUExtract(uint(abs_quant_texels1.y), q_1, 1), spvBitfieldUExtract(uint(abs_quant_texels1.z), q_1, 1), spvBitfieldUExtract(uint(abs_quant_texels1.w), q_1, 1));
            s0 = s0 << uint4(0u, 1u, 2u, 3u);
            s1 = s1 << uint4(4u, 5u, 6u, 7u);
            s = ((((((s0.x | s0.y) | s0.z) | s0.w) | s1.x) | s1.y) | s1.z) | s1.w;
            uint _983 = byte_offset;
            byte_offset = _983 + uint(1);
            uint param_21 = _983;
            uint param_22 = s;
            pw_store8_payload_data_pw_words8(param_21, param_22);
            q_1--;
        } while (q_1 >= 0);
    }
}

void comp_main()
{
    uint local_index = (pw_subgroup_id() * WaveGetLaneCount()) + WaveGetLaneIndex();
    uint block_local_index = spvBitfieldUExtract(local_index, 0, 3);
    uint block_x = spvBitfieldUExtract(local_index, 3, 2);
    uint block_y = spvBitfieldUExtract(local_index, 5, 2);
    uint param = block_local_index << uint(3);
    int2 local_coord = unswizzle8x8(param);
    int2 coord = int2(gl_WorkGroupID.xy) * int2(32, 32);
    coord += (int2(8, 8) * int2(int(block_x), int(block_y)));
    coord += local_coord;
    int2 block_index = (int2(4, 4) * int2(gl_WorkGroupID.xy)) + int2(int(block_x), int(block_y));
    float3 uv = float3(float2(coord) * registers_inv_resolution, registers_input_layer);
    float4 texels0 = uTexture.GatherRed(_uTexture_sampler, uv, int2(1, 1)).wxzy;
    float4 texels1 = uTexture.GatherRed(_uTexture_sampler, uv, int2(3, 1)).wxzy;
    precise float4 _1082 = texels0 * registers_quant_resolution;
    float4 scaled_texels0 = _1082;
    precise float4 _1087 = texels1 * registers_quant_resolution;
    float4 scaled_texels1 = _1087;
    bool in_bounds = all(bool2(block_index.x < registers_resolution_8x8_blocks.x, block_index.y < registers_resolution_8x8_blocks.y));
    if (in_bounds)
    {
        int2 param_1 = block_index;
        float2x4 param_2 = float2x4(float4(scaled_texels0), float4(scaled_texels1));
        encode_payload(param_1, param_2);
    }
}

[WaveSize(64)]
[numthreads(128, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
